// GENERATED by scripts/embed-migrations.mjs - do not edit.
// Source: drizzle/*.sql, produced by `pnpm db:generate`.

export interface EmbeddedMigration {
  tag: string
  statements: string[]
}

export const MIGRATIONS: readonly EmbeddedMigration[] = [
  {
    "tag": "0000_purple_silver_fox",
    "statements": [
      "CREATE TABLE `app_settings` (\r\n\t`key` text PRIMARY KEY NOT NULL,\r\n\t`value` text NOT NULL,\r\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL\r\n);",
      "CREATE TABLE `config_snapshots` (\r\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\r\n\t`project_path` text NOT NULL,\r\n\t`file_path` text NOT NULL,\r\n\t`content` text NOT NULL,\r\n\t`content_hash` text NOT NULL,\r\n\t`reason` text NOT NULL,\r\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL\r\n);",
      "CREATE INDEX `config_snapshots_file_idx` ON `config_snapshots` (`project_path`,`file_path`,`created_at`);",
      "CREATE TABLE `profiles` (\r\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\r\n\t`name` text NOT NULL,\r\n\t`root` text NOT NULL,\r\n\t`overlays` text DEFAULT '[]' NOT NULL,\r\n\t`access` text DEFAULT '[]' NOT NULL,\r\n\t`model` text,\r\n\t`effort` text,\r\n\t`permission_mode` text,\r\n\t`agent` text,\r\n\t`mcp` text DEFAULT '[]' NOT NULL,\r\n\t`opening_prompt` text,\r\n\t`pinned_order` integer,\r\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,\r\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL\r\n);",
      "CREATE UNIQUE INDEX `profiles_name_unique` ON `profiles` (`name`);",
      "CREATE TABLE `projects` (\r\n\t`path` text PRIMARY KEY NOT NULL,\r\n\t`name` text NOT NULL,\r\n\t`kind` text NOT NULL,\r\n\t`harness_path` text,\r\n\t`has_claude_dir` integer DEFAULT false NOT NULL,\r\n\t`inventory` text NOT NULL,\r\n\t`git` text,\r\n\t`last_seen_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL\r\n);",
      "CREATE INDEX `projects_harness_idx` ON `projects` (`harness_path`);"
    ]
  },
  {
    "tag": "0001_calm_cloak",
    "statements": [
      "CREATE TABLE `sessions` (\r\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\r\n\t`name` text NOT NULL,\r\n\t`cwd` text NOT NULL,\r\n\t`project_path` text,\r\n\t`argv` text DEFAULT '[]' NOT NULL,\r\n\t`status` text DEFAULT 'running' NOT NULL,\r\n\t`started_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,\r\n\t`ended_at` text,\r\n\t`duration_ms` integer,\r\n\t`exit_code` integer\r\n);",
      "CREATE INDEX `sessions_started_idx` ON `sessions` (`started_at`);",
      "CREATE INDEX `sessions_status_idx` ON `sessions` (`status`);"
    ]
  },
  {
    "tag": "0002_unknown_namorita",
    "statements": [
      "ALTER TABLE `sessions` ADD `profile_id` integer;"
    ]
  },
  {
    "tag": "0003_smart_nightmare",
    "statements": [
      "CREATE TABLE `history_index` (\r\n\t`file` text PRIMARY KEY NOT NULL,\r\n\t`bytes` integer NOT NULL,\r\n\t`indexed_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL\r\n);",
      "CREATE TABLE `history_prompts` (\r\n\t`seq` integer PRIMARY KEY NOT NULL,\r\n\t`session_id` text NOT NULL,\r\n\t`project` text NOT NULL,\r\n\t`at` integer NOT NULL,\r\n\t`text` text NOT NULL\r\n);",
      "CREATE INDEX `history_prompts_session_idx` ON `history_prompts` (`session_id`,`seq`);",
      "CREATE TABLE `history_sessions` (\r\n\t`session_id` text PRIMARY KEY NOT NULL,\r\n\t`project` text NOT NULL,\r\n\t`project_key` text NOT NULL,\r\n\t`prompt_count` integer NOT NULL,\r\n\t`first_at` integer NOT NULL,\r\n\t`last_at` integer NOT NULL,\r\n\t`first_prompt` text NOT NULL,\r\n\t`transcript_file` text,\r\n\t`transcript_bytes` integer,\r\n\t`project_exists` integer DEFAULT false NOT NULL\r\n);",
      "CREATE INDEX `history_sessions_last_idx` ON `history_sessions` (`last_at`);",
      "CREATE INDEX `history_sessions_project_idx` ON `history_sessions` (`project_key`,`last_at`);"
    ]
  },
  {
    "tag": "0004_tan_naoko",
    "statements": [
      "CREATE TABLE `usage_index` (\r\n\t`file` text PRIMARY KEY NOT NULL,\r\n\t`bytes` integer NOT NULL,\r\n\t`rows` integer DEFAULT 0 NOT NULL,\r\n\t`indexed_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL\r\n);",
      "CREATE TABLE `usage_messages` (\r\n\t`uuid` text PRIMARY KEY NOT NULL,\r\n\t`at` integer NOT NULL,\r\n\t`model` text NOT NULL,\r\n\t`input_tokens` integer DEFAULT 0 NOT NULL,\r\n\t`output_tokens` integer DEFAULT 0 NOT NULL,\r\n\t`cache_write_5m_tokens` integer DEFAULT 0 NOT NULL,\r\n\t`cache_write_1h_tokens` integer DEFAULT 0 NOT NULL,\r\n\t`cache_read_tokens` integer DEFAULT 0 NOT NULL\r\n);",
      "CREATE INDEX `usage_messages_at_idx` ON `usage_messages` (`at`,`model`);"
    ]
  },
  {
    "tag": "0005_puzzling_pete_wisdom",
    "statements": [
      "CREATE TABLE `pr_repos` (\r\n\t`path` text PRIMARY KEY NOT NULL,\r\n\t`url` text,\r\n\t`slug` text,\r\n\t`checked_at` text,\r\n\t`fetched_at` text,\r\n\t`error` text\r\n);",
      "CREATE TABLE `pull_requests` (\r\n\t`slug` text NOT NULL,\r\n\t`number` integer NOT NULL,\r\n\t`summary` text NOT NULL,\r\n\t`detail` text,\r\n\t`fetched_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,\r\n\t`detail_fetched_at` text,\r\n\tPRIMARY KEY(`slug`, `number`)\r\n);"
    ]
  },
  {
    "tag": "0006_perfect_pestilence",
    "statements": [
      "ALTER TABLE `pull_requests` ADD `diff` text;"
    ]
  },
  {
    "tag": "0007_pink_tinkerer",
    "statements": [
      "CREATE TABLE `transcript_index` (\r\n\t`file` text PRIMARY KEY NOT NULL,\r\n\t`bytes` integer NOT NULL,\r\n\t`messages` integer DEFAULT 0 NOT NULL,\r\n\t`indexed_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL\r\n);",
      "CREATE TABLE `transcript_messages` (\r\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\r\n\t`uuid` text NOT NULL,\r\n\t`session_id` text NOT NULL,\r\n\t`role` text NOT NULL,\r\n\t`at` integer NOT NULL,\r\n\t`body` blob NOT NULL,\r\n\t`compressed` integer DEFAULT false NOT NULL,\r\n\t`raw_bytes` integer DEFAULT 0 NOT NULL,\r\n\t`stored_bytes` integer DEFAULT 0 NOT NULL\r\n);",
      "CREATE UNIQUE INDEX `transcript_messages_uuid_unique` ON `transcript_messages` (`uuid`);",
      "CREATE INDEX `transcript_messages_session_idx` ON `transcript_messages` (`session_id`,`at`,`id`);",
      "CREATE TABLE `transcript_sessions` (\r\n\t`session_id` text PRIMARY KEY NOT NULL,\r\n\t`source_file` text NOT NULL,\r\n\t`state` text DEFAULT 'archived' NOT NULL,\r\n\t`first_at` integer,\r\n\t`last_at` integer,\r\n\t`message_count` integer DEFAULT 0 NOT NULL,\r\n\t`raw_bytes` integer DEFAULT 0 NOT NULL,\r\n\t`stored_bytes` integer DEFAULT 0 NOT NULL,\r\n\t`captured_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,\r\n\t`evicted_at` text\r\n);",
      "CREATE INDEX `transcript_sessions_oldest_idx` ON `transcript_sessions` (`state`,`last_at`);",
      "-- Everything below this line is HAND-WRITTEN and drizzle-kit did not produce it.\r\n-- drizzle-kit does not model virtual tables: it cannot generate an FTS5 table\r\n-- and it cannot see one that already exists, so it will neither recreate nor\r\n-- drop what follows. `pnpm db:generate` re-embeds whatever is in this folder,\r\n-- so this survives regeneration - but a later migration that needs to touch\r\n-- `transcript_fts` has to carry its own hand-written SQL in the same way. The\r\n-- reasoning is in `schema.ts`, under the three tables above.\r\n--\r\n-- `content=''` because the message text is not stored in plain form anywhere:\r\n-- `transcript_messages.body` is a compressed blob, so there is no column for an\r\n-- external-content FTS table to read and no column an INSERT trigger could read\r\n-- either. The index is written in code, beside the row it indexes and inside\r\n-- the same transaction (`store/archive.ts`).\r\n--\r\n-- `contentless_delete=1` is what makes the DELETE below legal - without it\r\n-- SQLite refuses to delete from a contentless FTS5 table, because it does not\r\n-- hold the text it would need to un-index. SQLite 3.43+; better-sqlite3 13\r\n-- bundles 3.53.\r\n--\r\n-- `unicode61 remove_diacritics 2` is the default tokenizer stated rather than\r\n-- assumed, so a future SQLite changing its default cannot silently re-tokenize\r\n-- an index nothing rebuilds.\r\nCREATE VIRTUAL TABLE `transcript_fts` USING fts5(\r\n  text,\r\n  content='',\r\n  contentless_delete=1,\r\n  tokenize=\"unicode61 remove_diacritics 2\"\r\n);",
      "-- The DELETE is a trigger and the INSERT is not, and the asymmetry is the\r\n-- design. A delete needs only `old.id`, and eviction is the one path that would\r\n-- otherwise leave index entries pointing at messages that no longer exist - a\r\n-- search that returned rowids the message table cannot resolve. Putting it in\r\n-- the schema means it cannot be forgotten by a caller.\r\nCREATE TRIGGER `transcript_fts_delete` AFTER DELETE ON `transcript_messages` BEGIN\r\n  DELETE FROM `transcript_fts` WHERE rowid = old.`id`;\r\nEND;"
    ]
  },
  {
    "tag": "0008_lyrical_yellow_claw",
    "statements": [
      "ALTER TABLE `sessions` ADD `label` text;",
      "ALTER TABLE `sessions` ADD `branch` text;"
    ]
  },
  {
    "tag": "0009_wet_ozymandias",
    "statements": [
      "CREATE TABLE `history_names` (\r\n\t`session_id` text PRIMARY KEY NOT NULL,\r\n\t`name` text NOT NULL,\r\n\t`renamed_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL\r\n);",
      "ALTER TABLE `history_prompts` ADD `title_rank` integer;",
      "ALTER TABLE `history_sessions` ADD `title_prompt` text;"
    ]
  },
  {
    "tag": "0010_shocking_starbolt",
    "statements": [
      "ALTER TABLE `projects` ADD `template` text;"
    ]
  },
  {
    "tag": "0011_brave_senator_kelly",
    "statements": [
      "ALTER TABLE `sessions` ADD `claude_session_id` text;"
    ]
  },
  {
    "tag": "0012_previous_lifeguard",
    "statements": [
      "ALTER TABLE `profiles` ADD `target` text;"
    ]
  }
]
